add: User identity negotiation
Enet4/dicom-rs pull request #402
Opened 2023-08-21 18:52 UTC by nicholasrussell

Hello,

Looking for your feedback in adding some of the [user identity negotiation](https://dicom.nema.org/medical/dicom/current/output/chtml/part07/sect_D.3.3.7.html) options.

In order to keep this minimal, I added the entrypoint into retrieving this data into the existing AccessControl trait. The downside being that it breaks the interface.

Thanks

2023-08-21 19:05 UTC, slimjim49j approved these changes

2023-08-22 08:42 UTC, Enet4 commented
Hello! Thank you for the pull request! It is great to see an initiative towards the integration on authorization mechanisms in DICOM-rs.

2024-03-13 18:09 UTC, Enet4 requested changes
Hello @nicholasrussel! I am adding this contribution as a candidate for DICOM-rs 0.7.0, but we may need a reiteration of the code first. Please see the suggestions inline, and let me know your availability to work on this.

If you also have any ideas for testing the changes in a real scenario, I would be grateful to know. The PACS archives I usually work with do not feature user identity negotiation.

2024-03-13 18:09 UTC, Enet4 commented on ul/src/pdu/mod.rs
> +        }
```suggestion
    fn from(user_identity_type: u8) -> Option<Self> {
        match user_identity_type {
            1 => Some(Self::Username),
            2 => Some(Self::UsernamePassword),
            3 => Some(Self::KerberosServiceTicket),
            4 => Some(Self::SamlAssertion),
            5 => Some(Self::Jwt),
            _ => None,
        }
```

2024-03-13 18:09 UTC, Enet4 commented on ul/src/pdu/mod.rs
> +            Self::Unsupported => 0,
```suggestion
            Self::SamlAssertion => 4,
            Self::Jwt => 5,
```

2024-03-13 18:09 UTC, Enet4 commented on ul/src/pdu/reader.rs
> +                            UserIdentityType::from(user_identity_type),
Here we would either change `UserIdentity` to cover the possibility of an unknown user identity type code, or skip the variable with a warning.

2024-03-24 09:52 UTC, Enet4 commented on ul/src/association/client.rs
> +        if username.is_empty() {
Never mind, I read this incorrectly.

2024-04-13 10:04 UTC, Enet4 approved these changes
Despite there being gaps in the ecosystem for full authentication support, there is interest in expanding the `ul` crate with the knowledge of user identity parts, plus the extra of making these available in the `dicom-storescu` tool. This appears to be in order, so I will merge it onto the 0.7 milestone. Much appreciated! :+1:

2024-04-13 10:04 UTC, merged